spring.application.name=raizesdonordeste

# Conexão com o postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/raizesdonordeste
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true